/// Flutter icons BrandIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrandIcons
///      fonts:
///       - asset: fonts/BrandIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BrandIcons {
  BrandIcons._();

  static const _kFontFam = 'BrandIcons';
  static const String? _kFontPkg = null;

  static const IconData amazon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audible = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger_b = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dev = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_in = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xf23a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_m = IconData(0xf3c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
